#!/bin/bash
set -e

source /usr/share/yunohost/helpers

app=$YNH_APP_INSTANCE_NAME

# Backup app directory
ynh_backup --src_path="/opt/$app"

# Note: We don't backup Postfix config files as they're shared
# The install script will recreate the necessary entries