#!/bin/bash
set -e

source /usr/share/yunohost/helpers

app=$YNH_APP_INSTANCE_NAME
local_part=$(ynh_app_setting_get $app local_part)

# Remove cron job
rm -f "/etc/cron.d/${app}"

# Delete YunoHost user
if yunohost user list --output-as json | jq -e ".users.\"$local_part\"" >/dev/null 2>&1; then
    yunohost user delete "$local_part" || true
fi

# Delete system user and files
ynh_system_user_delete $app || true
rm -rf /opt/$app